services:
  client:
    image: website/client
    build: ./client
    ports:
      - 3000:3000
    command: yarn dev

  server:
    image: website/server
    build:
      context: ./server
      target: dev
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongodb_config:
