services:
  client:
    image: website/client
    build:
      context: ./client
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  server:
    image: website/server
    build:
      context: ./server
      target: dev
    ports:
      - 8080:8080
      - 4000:4000
      - 9229:9229
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongodb_config:
